# Site settings
title: Uncreative IT blog title
email: henry@hgrover.com
description: > # this means to ignore newlines until "baseurl:"
    My basic site, created using Jekyll and hosted on Github pages. I hope to add to it soon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hgrover.com" # the base hostname & protocol for your site
github_username:  henrygrover

# Build settings
markdown: kramdown
